# Generated by Django 5.2.17 on 2026-09-15 09:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cohorts', '0001_initial'),
        ('students', '0001_initial'),
        ('supervisors', '0001_initial'),
        ('tracks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PLACED', 'Placed'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='PLACED', max_length=20)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='cohorts.cohort')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='students.studentprofile')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='supervisors.supervisorprofile')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='tracks.track')),
            ],
            options={
                'ordering': ['-start_date', 'student__registration_number'],
                'indexes': [models.Index(fields=['status', 'start_date'], name='placement_status_start_idx'), models.Index(fields=['supervisor', 'status'], name='placement_supervisor_idx'), models.Index(fields=['cohort', 'status'], name='placement_cohort_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='placement_valid_date_range'), models.UniqueConstraint(condition=models.Q(('status', 'COMPLETED'), _negated=True), fields=('student',), name='one_current_placement_per_student')],
            },
        ),
    ]
