# Generated by Django 5.2.17 on 2026-09-15 09:31

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('programme', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['registration_number'],
                'indexes': [models.Index(fields=['department'], name='student_department_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('registration_number'), name='student_reg_number_ci_unique')],
            },
        ),
    ]
