# Generated by Django 5.2.17 on 2026-09-15 09:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_number', models.PositiveIntegerField()),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('activities_completed', models.TextField()),
                ('skills_learned', models.TextField()),
                ('challenges_faced', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed')], default='DRAFT', max_length=20)),
                ('supervisor_feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='placements.placement')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start_date', '-created_at'],
                'indexes': [models.Index(fields=['status', 'submitted_at'], name='report_status_submitted_idx'), models.Index(fields=['placement', 'week_number'], name='report_placement_week_idx')],
                'constraints': [models.UniqueConstraint(fields=('placement', 'week_number'), name='unique_report_placement_week'), models.CheckConstraint(condition=models.Q(('week_number__gte', 1)), name='report_week_positive'), models.CheckConstraint(condition=models.Q(('week_end_date__gte', models.F('week_start_date'))), name='report_valid_date_range')],
            },
        ),
    ]
